### ISSUE TITLE
Assign to project but no column

### ISSUE THREAD

**Issue by mattfelten** [srggrs/assign-one-project-github-action#60]
If you add an Issue to a Project manually, it goes into an `Awaiting triage` state. Is there a way for this action to allow that? From what I read, if you leave off specifying a column, it will default to To Do (which I'm not using, so not sure what would happen there).

**Comment by srggrs** [comment]
Hi,

not too sure what is `Awaiting triage` but when you create a project, you can choose some template, which have column names (and associated automation eventually)... can't put `Awaiting triage` as the column name in the action? is your project dashboard looking like [this](https://github.com/dnnsoftware/Dnn.Platform/projects/2)

**Comment by mattfelten** [comment]
From an Issue page, if you add the Issue to a project without selecting a column, you can see it gets an `Awaiting triage` state
![](https://p195.p4.n0.cdn.getcloudapp.com/items/rRukyQ78/8f43c434-375e-4503-81b2-e1b337e48768.png?v=fd53311946e71798f31922d3a5a30fa6)

From the Project page, you'll now see the Add New button shows a count of how many issues are in this triaging state.
![](https://p195.p4.n0.cdn.getcloudapp.com/items/yAu67Qr5/145ddc31-af97-4811-b1d8-62c1d47edba7.png?v=6fc56d1a3f3ec4d3d6a9398f0deb5f51)

Clicking that button opens the normal issue search panel but with a Triage section open
![](https://p195.p4.n0.cdn.getcloudapp.com/items/kpu7PW6l/f2f70add-6899-44ce-9289-fc5227d7f821.png?v=923a95e06d777854eb0251fedd32885e)

---

I'd like to use the built-in triaging feature in GitHub with this Action.

**Comment by srggrs** [comment]
Hi,

I was able to re-create your issue. In your case you create a project without any columns, and it's true that you can manually add the issue to the project but when you open the project, because no column are created yet, the issue "card" does not appear any where.
![image](https://user-images.githubusercontent.com/34258464/110231729-98674680-7f6d-11eb-9fce-835c7716ba41.png)

and here

![image](https://user-images.githubusercontent.com/34258464/110231746-ae750700-7f6d-11eb-9159-1df42a13d96d.png)

It's true that the "triage" section appears but the issue does not appear to your project because you need at least one column. So not sure what is your use case, but if you want the issue to automatically assign to "Backlog" project (for example) you could create a column "Triage" in that project and use that in your workflow file (I use terminology from the Agile projet management in software development). 

Hope that make sense. Let me know if I can help you further.

Cheers,
Sergio
